#!/usr/bin/env node

'use strict';

var c = require("skilstak-colors");

var printPlain = function(helloworld) {
  console.log(c.clear + c.rc() + helloworld + c.x);
}

var forcePush = function (hansoloisstupid) {
console.log(c.clear + c.rc() + hansoloisstupid + c.x);
}
var runAndGetSliced = function (LukeSkywalkerisfound) {
console.log(c.clear + c.multi(LukeSkywalkerisfound));
}                              
 var printBoringLoop = function (Youknowwhativecomefor) {
while (true){
iconsole.log(Youknowwhativecomefor);
}
 }



printPlain("hello world")
forcePush("han solo is stupid)
runAndGetSliced("Luke Skywalkerisfound")
printBoringLoop("You know what ive come for")








